# eureka:
#     instance:
#         leaseRenewalIntervalInSeconds: 1
#         leaseExpirationDurationInSeconds: 2
#     client:
#         serviceUrl:
#             defaultZone: http://eureka:8095/eureka/
#         healthcheck:
#             enabled: true
#         lease:
#             duration: 5
#         register-with-eureka: true
#         fetch-registry: true

# management:
#     security:
#         enabled: false
        
# Alert-manager:
#     spring:
#       data:
#         influx:
#           database: metrics
#           host: localhost
#           port: 8086
#           uri: influx://localhost:8086/metrics
          
# Monitoring-server:
#     spring:
#         influxdb:
#             url: http://influxdb:8086
#             username: tanu
#             password: password
#             database: metricsData



#     clientUrl: http://client-server:8082
#     containerUrl: http://agenttodocker:9001
#     warUrl: http://war-client:8081

#     cpuCoresInterval: 10000
#     cpuTempInterval: 10000
#     cpuUsageInterval: 10000
#     networkInterval: 10000
#     threadInterval: 10000
#     diskInterval: 10000
#     ramInterval: 10000
#     healthInterval: 1000
#     httpInterval: 10000
#     containerInterval: 10000

#     warCpuCoresInterval: 10000
#     warCpuTempInterval: 10000
#     warCpuUsageInterval: 10000
#     warNetworkInterval: 10000
#     warThreadInterval: 10000
#     warRamInterval: 10000
