spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanushareddy182@gmail.com
    password: Harbabamine
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      database: details
